/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Controller.Controlador;

/**
 *
 * @author diegoplays
 */
public class AfegirCategoria extends javax.swing.JDialog {

    static Controlador cnt;

    /**
     * Constructor d'AfegirCategoria. Inicialitza els seus components.
     * @param cnt Controlador
     * @param parent JFrame pare
     * @param modal si aquest JDialog apareix a sobre de tot.
     */
    public AfegirCategoria(Controlador cnt, java.awt.Frame parent, boolean modal) {
        super(parent);
        initComponents();
        AfegirCategoria.cnt = cnt;
        setModal(modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The cntent of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldCategoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ButtonAfegir = new javax.swing.JButton();
        LabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TextFieldCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFieldCategoriaFocusLost(evt);
            }
        });
        TextFieldCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldCategoriaMouseClicked(evt);
            }
        });

        jLabel1.setText("Nom categoria:");

        ButtonAfegir.setText("Afegir");
        ButtonAfegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAfegirActionPerformed(evt);
            }
        });

        LabelError.setForeground(new java.awt.Color(204, 0, 0));
        LabelError.setText("El nom ha de contenir entre 3 i 50 caràcters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(LabelError))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(TextFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(ButtonAfegir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LabelError)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonAfegir)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldCategoriaFocusLost
        int lenTxt = TextFieldCategoria.getText().length();
        if (lenTxt < 3 || lenTxt > 50) {
            LabelError.setText("El nom ha de contenir entre 3 i 50 caràcters");
            ButtonAfegir.setEnabled(false);
        } else {
            LabelError.setText("");
            ButtonAfegir.setEnabled(true);
        }
    }//GEN-LAST:event_TextFieldCategoriaFocusLost

    private void ButtonAfegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAfegirActionPerformed
        int lenTxt = TextFieldCategoria.getText().length();
        if (ButtonAfegir.isEnabled() && lenTxt >= 3 && lenTxt <= 50) {
            cnt.afegirUnaCategoria(TextFieldCategoria.getText());
            dispose();
        }
    }//GEN-LAST:event_ButtonAfegirActionPerformed

    private void TextFieldCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldCategoriaMouseClicked
        int lenTxt = TextFieldCategoria.getText().length();
        if (lenTxt >= 3 && lenTxt <= 50) {
            LabelError.setVisible(false);
            ButtonAfegir.setEnabled(true);
        }
    }//GEN-LAST:event_TextFieldCategoriaMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AfegirCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AfegirCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AfegirCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AfegirCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                AfegirCategoria dialog = new AfegirCategoria(cnt, new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAfegir;
    private javax.swing.JLabel LabelError;
    private javax.swing.JTextField TextFieldCategoria;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
