/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Controller.Controlador;
import java.sql.SQLException;
import javax.swing.table.TableModel;

/**
 *
 * @author diegoplays
 */
public final class MostraVaixells extends javax.swing.JDialog {

    java.awt.Frame parent;
    Controlador cnt;
    TableModel tm;

    public MostraVaixells(java.awt.Frame parent, boolean modal, Controlador cnt) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        this.cnt = cnt;
        MostrarCategories();
        tm = setDefault();
        MostrarOrdres(tm);
    }

    /**
     * Mostra totes les categories dins d'un ComboBox, incloent-hi una que
     * representa qualsevol categoria.
     */
    public void MostrarCategories() {
        ComboBoxCategoria.removeAllItems();
        ComboBoxCategoria.addItem("-- Tot --");
        cnt.getCategories("nom").forEach((c) -> {
            ComboBoxCategoria.addItem(c.getNom());
        });
    }

    /**
     * Mostra totes les columnes segons les quals es podria ordenar,
     * dins d'un ComboBox.
     * @param tm retorna el TableModel de la Taula.
     */
    public void MostrarOrdres(TableModel tm) {
        String[] array = cnt.getTaulaOrdre(tm);
        for (String x : array) {
            ComboBoxOrdre.addItem(x);
        }
    }

    /**
     * Inicialitza el TableModel quan encara no s'han seleccionat valors.
     * @return retorna el TableModel de la Taula.
     */
    public TableModel setDefault() {
        try {
            tm = cnt.getVaixellsTable();
            Taula.setModel(tm);
            return tm;
        } catch (SQLException ex) {
            System.out.println(ex.toString());
            return null;
        }
    }

    /**
     * Actualitza el TableModel segons el que l'usuari hagi seleccionat tant al
     * ComboBox de filtre per categoria com el de l'ordre per columna.
     */
    public void setInfoCategories() {
        try {
            tm = cnt.getVaixellsTable(ComboBoxOrdre.getSelectedItem().toString(),
                    cnt.getIdCategoria(cnt.getCatByOrderIndex(ComboBoxCategoria.getSelectedIndex() - 1)));
            Taula.setModel(tm);
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The cntent of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPanel1 = new javax.swing.JScrollPane();
        Taula = new javax.swing.JTable();
        ComboBoxCategoria = new javax.swing.JComboBox<>();
        LabelCategoria = new javax.swing.JLabel();
        LabelImport = new javax.swing.JLabel();
        ComboBoxOrdre = new javax.swing.JComboBox<>();
        LabelOrdre = new javax.swing.JLabel();
        ButtonModificar = new javax.swing.JButton();
        ButtonEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Taula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Taula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TaulaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TaulaFocusLost(evt);
            }
        });
        ScrollPanel1.setViewportView(Taula);

        ComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCategoriaActionPerformed(evt);
            }
        });

        LabelCategoria.setText("Categoria:");

        ComboBoxOrdre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxOrdreActionPerformed(evt);
            }
        });

        LabelOrdre.setText("Ordre:");

        ButtonModificar.setText("Modificar");
        ButtonModificar.setEnabled(false);
        ButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarActionPerformed(evt);
            }
        });

        ButtonEliminar.setText("Eliminar");
        ButtonEliminar.setEnabled(false);
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("TAULA DE VAIXELLS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(LabelCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelOrdre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxOrdre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ScrollPanel1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(ButtonModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelImport, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ButtonEliminar)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCategoria)
                    .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxOrdre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelOrdre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonModificar)
                            .addComponent(ButtonEliminar))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCategoriaActionPerformed
        if (ComboBoxOrdre.getSelectedIndex() == -1) {
            setDefault();
        } else {
            setInfoCategories();
        }
    }//GEN-LAST:event_ComboBoxCategoriaActionPerformed

    private void ComboBoxOrdreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxOrdreActionPerformed
        setInfoCategories();
//        setDefault();
    }//GEN-LAST:event_ComboBoxOrdreActionPerformed

    private void ButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarActionPerformed
        if (Taula.getSelectedRow() == -1) {
            ButtonEliminar.setEnabled(false);
            ButtonModificar.setEnabled(false);
        } else {
            cnt.ObrirFormulari(parent, getIdVaixellSeleccionat());
            setInfoCategories();
        }
    }//GEN-LAST:event_ButtonModificarActionPerformed

    private int getIdVaixellSeleccionat() {
        return Integer.parseInt(Taula.getValueAt(Taula.getSelectedRow(), 0).toString());
    }
    private void TaulaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TaulaFocusGained
        if (Taula.getSelectedRow() != -1) {
            ButtonEliminar.setEnabled(true);
            ButtonModificar.setEnabled(true);
        }
    }//GEN-LAST:event_TaulaFocusGained

    private void TaulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TaulaFocusLost
        if (Taula.getSelectedRow() == -1) {
            ButtonEliminar.setEnabled(false);
            ButtonModificar.setEnabled(false);
        }
    }//GEN-LAST:event_TaulaFocusLost

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
        if (Taula.getSelectedRow() != -1) {
            cnt.eliminarVaixell(getIdVaixellSeleccionat());
            setInfoCategories();
        } // Double IF per a comprovar tant si s'elimina una categoria com si no
        if (Taula.getSelectedRow() == -1) {
            ButtonEliminar.setEnabled(false);
            ButtonModificar.setEnabled(false);
        }
    }//GEN-LAST:event_ButtonEliminarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MostraVaixells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MostraVaixells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MostraVaixells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MostraVaixells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                MostraVaixells dialog = new MostraVaixells(new javax.swing.JFrame(), true, null);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JButton ButtonModificar;
    private javax.swing.JComboBox<String> ComboBoxCategoria;
    private javax.swing.JComboBox<String> ComboBoxOrdre;
    private javax.swing.JLabel LabelCategoria;
    private javax.swing.JLabel LabelImport;
    private javax.swing.JLabel LabelOrdre;
    private javax.swing.JScrollPane ScrollPanel1;
    private javax.swing.JTable Taula;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
